# Generated by Django 3.2.16 on 2022-11-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Transfer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
