# Generated by Django 3.2.16 on 2022-11-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Transfer_app', '0002_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='media/Lenna.png', upload_to='result'),
        ),
    ]
