# Generated by Django 3.2.16 on 2022-12-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art_Transfer_app', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='output',
            field=models.ImageField(default='C:/Users/mkom7/Documents/GitHub/art-transfer-web/back/AI_module/imgs/horse2zebra.gif', upload_to='output'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='C:/Users/mkom7/Documents/GitHub/art-transfer-web/back/AI_module/imgs/horse2zebra.gif', upload_to='input'),
        ),
    ]
